# Generated by Django 4.0.6 on 2022-08-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sulg',
            new_name='slug',
        ),
    ]
